/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : PingServer_PingFSM_sm.sm
 */

#include "urn_jts_PingServer_1_0/Messages/MessageSet.h"
#include "urn_jts_PingServer_1_0/PingServer_PingFSM.h"
#include "include/urn_jts_PingServer_1_0/PingServer_PingFSM_sm.h"

using namespace statemap;

namespace urn_jts_PingServer_1_0
{
    // Static class declarations.
    PingServer_PingFSM_SM_Ready PingServer_PingFSM_SM::Ready("PingServer_PingFSM_SM::Ready", 0);
    PingServer_PingFSM_SM_Internally_Generated_State_DO_NOT_USE PingServer_PingFSM_SM::Internally_Generated_State_DO_NOT_USE("PingServer_PingFSM_SM::Internally_Generated_State_DO_NOT_USE", 1);

    void PingServer_PingFSMState::QueryHeartbeatPulseTransition(PingServer_PingFSMContext& context)
    {
        Default(context);
        return;
    }

    void PingServer_PingFSMState::Default(PingServer_PingFSMContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void PingServer_PingFSM_SM_Ready::QueryHeartbeatPulseTransition(PingServer_PingFSMContext& context)
    {
        PingServer_PingFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PingServer_PingFSM_SM::Ready"
            << std::endl;
        }

        PingServer_PingFSMState& endState = context.getState();

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PingServer_PingFSM_SM::Ready::QueryHeartbeatPulseTransition()"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.ReportHeartbeatPulseAction();
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : PingServer_PingFSM_SM::Ready::QueryHeartbeatPulseTransition()"
                    << std::endl;
            }

            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void PingServer_PingFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryHeartbeatPulseTransition(PingServer_PingFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PingServer_PingFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PingServer_PingFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryHeartbeatPulseTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PingServer_PingFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryHeartbeatPulseTransition()"
                << std::endl;
        }


        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
